name: KMP Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  validate:
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            tasks: ":adhan:linuxX64Test :adhan:jvmTest :adhan:jsTest :adhan:wasmJsTest :samples:build"

          - name: apple-arm64
            os: macos-latest
            tasks: ":adhan:iosSimulatorArm64Test :adhan:macosArm64Test"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6.0.3
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Run ${{ matrix.name }} tests
        run: ./gradlew --no-configure-on-demand ${{ matrix.tasks }}
      - uses: codecov/codecov-action@v7.0.0
        if: matrix.os == 'ubuntu-latest'
