name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [11, 17]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run test with Gradle Wrapper
      run: ./gradlew --debug test
    - uses: codecov/codecov-action@v3

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [11, 17]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
